remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PadBoy
description: Launchpadder website

show_downloads: true

github:
  zip_url: pdby.github.io/project.html
  another_url: pdby.github.io/project.md
